// GENERATED FILE -- do not hand-edit. Produced by
// apps/mobile/scripts/generate-country-names.mjs from libphonenumber-js's
// getCountries() + Node's own Intl.DisplayNames (see that script's own
// header comment for why this is pre-generated rather than resolved at
// runtime). Re-run the script to regenerate if libphonenumber-js's country
// list changes.

export interface CountryNames {
  en: string;
  fr: string;
}

export const COUNTRY_NAMES: Record<string, CountryNames> = {
  AC: { en: "Ascension Island", fr: "Île de l’Ascension" },
  AD: { en: "Andorra", fr: "Andorre" },
  AE: { en: "United Arab Emirates", fr: "Émirats arabes unis" },
  AF: { en: "Afghanistan", fr: "Afghanistan" },
  AG: { en: "Antigua & Barbuda", fr: "Antigua-et-Barbuda" },
  AI: { en: "Anguilla", fr: "Anguilla" },
  AL: { en: "Albania", fr: "Albanie" },
  AM: { en: "Armenia", fr: "Arménie" },
  AO: { en: "Angola", fr: "Angola" },
  AR: { en: "Argentina", fr: "Argentine" },
  AS: { en: "American Samoa", fr: "Samoa américaines" },
  AT: { en: "Austria", fr: "Autriche" },
  AU: { en: "Australia", fr: "Australie" },
  AW: { en: "Aruba", fr: "Aruba" },
  AX: { en: "Åland Islands", fr: "Îles Åland" },
  AZ: { en: "Azerbaijan", fr: "Azerbaïdjan" },
  BA: { en: "Bosnia & Herzegovina", fr: "Bosnie-Herzégovine" },
  BB: { en: "Barbados", fr: "Barbade" },
  BD: { en: "Bangladesh", fr: "Bangladesh" },
  BE: { en: "Belgium", fr: "Belgique" },
  BF: { en: "Burkina Faso", fr: "Burkina Faso" },
  BG: { en: "Bulgaria", fr: "Bulgarie" },
  BH: { en: "Bahrain", fr: "Bahreïn" },
  BI: { en: "Burundi", fr: "Burundi" },
  BJ: { en: "Benin", fr: "Bénin" },
  BL: { en: "St. Barthélemy", fr: "Saint-Barthélemy" },
  BM: { en: "Bermuda", fr: "Bermudes" },
  BN: { en: "Brunei", fr: "Brunei" },
  BO: { en: "Bolivia", fr: "Bolivie" },
  BQ: { en: "Caribbean Netherlands", fr: "Pays-Bas caribéens" },
  BR: { en: "Brazil", fr: "Brésil" },
  BS: { en: "Bahamas", fr: "Bahamas" },
  BT: { en: "Bhutan", fr: "Bhoutan" },
  BW: { en: "Botswana", fr: "Botswana" },
  BY: { en: "Belarus", fr: "Biélorussie" },
  BZ: { en: "Belize", fr: "Belize" },
  CA: { en: "Canada", fr: "Canada" },
  CC: { en: "Cocos (Keeling) Islands", fr: "Îles Cocos" },
  CD: { en: "Congo - Kinshasa", fr: "Congo-Kinshasa" },
  CF: { en: "Central African Republic", fr: "République centrafricaine" },
  CG: { en: "Congo - Brazzaville", fr: "Congo-Brazzaville" },
  CH: { en: "Switzerland", fr: "Suisse" },
  CI: { en: "Côte d’Ivoire", fr: "Côte d’Ivoire" },
  CK: { en: "Cook Islands", fr: "Îles Cook" },
  CL: { en: "Chile", fr: "Chili" },
  CM: { en: "Cameroon", fr: "Cameroun" },
  CN: { en: "China", fr: "Chine" },
  CO: { en: "Colombia", fr: "Colombie" },
  CR: { en: "Costa Rica", fr: "Costa Rica" },
  CU: { en: "Cuba", fr: "Cuba" },
  CV: { en: "Cape Verde", fr: "Cap-Vert" },
  CW: { en: "Curaçao", fr: "Curaçao" },
  CX: { en: "Christmas Island", fr: "Île Christmas" },
  CY: { en: "Cyprus", fr: "Chypre" },
  CZ: { en: "Czechia", fr: "Tchéquie" },
  DE: { en: "Germany", fr: "Allemagne" },
  DJ: { en: "Djibouti", fr: "Djibouti" },
  DK: { en: "Denmark", fr: "Danemark" },
  DM: { en: "Dominica", fr: "Dominique" },
  DO: { en: "Dominican Republic", fr: "République dominicaine" },
  DZ: { en: "Algeria", fr: "Algérie" },
  EC: { en: "Ecuador", fr: "Équateur" },
  EE: { en: "Estonia", fr: "Estonie" },
  EG: { en: "Egypt", fr: "Égypte" },
  EH: { en: "Western Sahara", fr: "Sahara occidental" },
  ER: { en: "Eritrea", fr: "Érythrée" },
  ES: { en: "Spain", fr: "Espagne" },
  ET: { en: "Ethiopia", fr: "Éthiopie" },
  FI: { en: "Finland", fr: "Finlande" },
  FJ: { en: "Fiji", fr: "Fidji" },
  FK: { en: "Falkland Islands", fr: "Îles Malouines" },
  FM: { en: "Micronesia", fr: "Micronésie" },
  FO: { en: "Faroe Islands", fr: "Îles Féroé" },
  FR: { en: "France", fr: "France" },
  GA: { en: "Gabon", fr: "Gabon" },
  GB: { en: "United Kingdom", fr: "Royaume-Uni" },
  GD: { en: "Grenada", fr: "Grenade" },
  GE: { en: "Georgia", fr: "Géorgie" },
  GF: { en: "French Guiana", fr: "Guyane française" },
  GG: { en: "Guernsey", fr: "Guernesey" },
  GH: { en: "Ghana", fr: "Ghana" },
  GI: { en: "Gibraltar", fr: "Gibraltar" },
  GL: { en: "Greenland", fr: "Groenland" },
  GM: { en: "Gambia", fr: "Gambie" },
  GN: { en: "Guinea", fr: "Guinée" },
  GP: { en: "Guadeloupe", fr: "Guadeloupe" },
  GQ: { en: "Equatorial Guinea", fr: "Guinée équatoriale" },
  GR: { en: "Greece", fr: "Grèce" },
  GT: { en: "Guatemala", fr: "Guatemala" },
  GU: { en: "Guam", fr: "Guam" },
  GW: { en: "Guinea-Bissau", fr: "Guinée-Bissau" },
  GY: { en: "Guyana", fr: "Guyana" },
  HK: { en: "Hong Kong SAR China", fr: "R.A.S. chinoise de Hong Kong" },
  HN: { en: "Honduras", fr: "Honduras" },
  HR: { en: "Croatia", fr: "Croatie" },
  HT: { en: "Haiti", fr: "Haïti" },
  HU: { en: "Hungary", fr: "Hongrie" },
  ID: { en: "Indonesia", fr: "Indonésie" },
  IE: { en: "Ireland", fr: "Irlande" },
  IL: { en: "Israel", fr: "Israël" },
  IM: { en: "Isle of Man", fr: "Île de Man" },
  IN: { en: "India", fr: "Inde" },
  IO: { en: "British Indian Ocean Territory", fr: "Territoire britannique de l’océan Indien" },
  IQ: { en: "Iraq", fr: "Irak" },
  IR: { en: "Iran", fr: "Iran" },
  IS: { en: "Iceland", fr: "Islande" },
  IT: { en: "Italy", fr: "Italie" },
  JE: { en: "Jersey", fr: "Jersey" },
  JM: { en: "Jamaica", fr: "Jamaïque" },
  JO: { en: "Jordan", fr: "Jordanie" },
  JP: { en: "Japan", fr: "Japon" },
  KE: { en: "Kenya", fr: "Kenya" },
  KG: { en: "Kyrgyzstan", fr: "Kirghizstan" },
  KH: { en: "Cambodia", fr: "Cambodge" },
  KI: { en: "Kiribati", fr: "Kiribati" },
  KM: { en: "Comoros", fr: "Comores" },
  KN: { en: "St. Kitts & Nevis", fr: "Saint-Christophe-et-Niévès" },
  KP: { en: "North Korea", fr: "Corée du Nord" },
  KR: { en: "South Korea", fr: "Corée du Sud" },
  KW: { en: "Kuwait", fr: "Koweït" },
  KY: { en: "Cayman Islands", fr: "Îles Caïmans" },
  KZ: { en: "Kazakhstan", fr: "Kazakhstan" },
  LA: { en: "Laos", fr: "Laos" },
  LB: { en: "Lebanon", fr: "Liban" },
  LC: { en: "St. Lucia", fr: "Sainte-Lucie" },
  LI: { en: "Liechtenstein", fr: "Liechtenstein" },
  LK: { en: "Sri Lanka", fr: "Sri Lanka" },
  LR: { en: "Liberia", fr: "Liberia" },
  LS: { en: "Lesotho", fr: "Lesotho" },
  LT: { en: "Lithuania", fr: "Lituanie" },
  LU: { en: "Luxembourg", fr: "Luxembourg" },
  LV: { en: "Latvia", fr: "Lettonie" },
  LY: { en: "Libya", fr: "Libye" },
  MA: { en: "Morocco", fr: "Maroc" },
  MC: { en: "Monaco", fr: "Monaco" },
  MD: { en: "Moldova", fr: "Moldavie" },
  ME: { en: "Montenegro", fr: "Monténégro" },
  MF: { en: "St. Martin", fr: "Saint-Martin" },
  MG: { en: "Madagascar", fr: "Madagascar" },
  MH: { en: "Marshall Islands", fr: "Îles Marshall" },
  MK: { en: "North Macedonia", fr: "Macédoine du Nord" },
  ML: { en: "Mali", fr: "Mali" },
  MM: { en: "Myanmar (Burma)", fr: "Myanmar (Birmanie)" },
  MN: { en: "Mongolia", fr: "Mongolie" },
  MO: { en: "Macao SAR China", fr: "R.A.S. chinoise de Macao" },
  MP: { en: "Northern Mariana Islands", fr: "Îles Mariannes du Nord" },
  MQ: { en: "Martinique", fr: "Martinique" },
  MR: { en: "Mauritania", fr: "Mauritanie" },
  MS: { en: "Montserrat", fr: "Montserrat" },
  MT: { en: "Malta", fr: "Malte" },
  MU: { en: "Mauritius", fr: "Maurice" },
  MV: { en: "Maldives", fr: "Maldives" },
  MW: { en: "Malawi", fr: "Malawi" },
  MX: { en: "Mexico", fr: "Mexique" },
  MY: { en: "Malaysia", fr: "Malaisie" },
  MZ: { en: "Mozambique", fr: "Mozambique" },
  NA: { en: "Namibia", fr: "Namibie" },
  NC: { en: "New Caledonia", fr: "Nouvelle-Calédonie" },
  NE: { en: "Niger", fr: "Niger" },
  NF: { en: "Norfolk Island", fr: "Île Norfolk" },
  NG: { en: "Nigeria", fr: "Nigeria" },
  NI: { en: "Nicaragua", fr: "Nicaragua" },
  NL: { en: "Netherlands", fr: "Pays-Bas" },
  NO: { en: "Norway", fr: "Norvège" },
  NP: { en: "Nepal", fr: "Népal" },
  NR: { en: "Nauru", fr: "Nauru" },
  NU: { en: "Niue", fr: "Niue" },
  NZ: { en: "New Zealand", fr: "Nouvelle-Zélande" },
  OM: { en: "Oman", fr: "Oman" },
  PA: { en: "Panama", fr: "Panama" },
  PE: { en: "Peru", fr: "Pérou" },
  PF: { en: "French Polynesia", fr: "Polynésie française" },
  PG: { en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  PH: { en: "Philippines", fr: "Philippines" },
  PK: { en: "Pakistan", fr: "Pakistan" },
  PL: { en: "Poland", fr: "Pologne" },
  PM: { en: "St. Pierre & Miquelon", fr: "Saint-Pierre-et-Miquelon" },
  PR: { en: "Puerto Rico", fr: "Porto Rico" },
  PS: { en: "Palestinian Territories", fr: "Territoires palestiniens" },
  PT: { en: "Portugal", fr: "Portugal" },
  PW: { en: "Palau", fr: "Palaos" },
  PY: { en: "Paraguay", fr: "Paraguay" },
  QA: { en: "Qatar", fr: "Qatar" },
  RE: { en: "Réunion", fr: "La Réunion" },
  RO: { en: "Romania", fr: "Roumanie" },
  RS: { en: "Serbia", fr: "Serbie" },
  RU: { en: "Russia", fr: "Russie" },
  RW: { en: "Rwanda", fr: "Rwanda" },
  SA: { en: "Saudi Arabia", fr: "Arabie saoudite" },
  SB: { en: "Solomon Islands", fr: "Îles Salomon" },
  SC: { en: "Seychelles", fr: "Seychelles" },
  SD: { en: "Sudan", fr: "Soudan" },
  SE: { en: "Sweden", fr: "Suède" },
  SG: { en: "Singapore", fr: "Singapour" },
  SH: { en: "St. Helena", fr: "Sainte-Hélène" },
  SI: { en: "Slovenia", fr: "Slovénie" },
  SJ: { en: "Svalbard & Jan Mayen", fr: "Svalbard et Jan Mayen" },
  SK: { en: "Slovakia", fr: "Slovaquie" },
  SL: { en: "Sierra Leone", fr: "Sierra Leone" },
  SM: { en: "San Marino", fr: "Saint-Marin" },
  SN: { en: "Senegal", fr: "Sénégal" },
  SO: { en: "Somalia", fr: "Somalie" },
  SR: { en: "Suriname", fr: "Suriname" },
  SS: { en: "South Sudan", fr: "Soudan du Sud" },
  ST: { en: "São Tomé & Príncipe", fr: "Sao Tomé-et-Principe" },
  SV: { en: "El Salvador", fr: "Salvador" },
  SX: { en: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)" },
  SY: { en: "Syria", fr: "Syrie" },
  SZ: { en: "Eswatini", fr: "Eswatini" },
  TA: { en: "Tristan da Cunha", fr: "Tristan da Cunha" },
  TC: { en: "Turks & Caicos Islands", fr: "Îles Turques-et-Caïques" },
  TD: { en: "Chad", fr: "Tchad" },
  TG: { en: "Togo", fr: "Togo" },
  TH: { en: "Thailand", fr: "Thaïlande" },
  TJ: { en: "Tajikistan", fr: "Tadjikistan" },
  TK: { en: "Tokelau", fr: "Tokelau" },
  TL: { en: "Timor-Leste", fr: "Timor oriental" },
  TM: { en: "Turkmenistan", fr: "Turkménistan" },
  TN: { en: "Tunisia", fr: "Tunisie" },
  TO: { en: "Tonga", fr: "Tonga" },
  TR: { en: "Türkiye", fr: "Turquie" },
  TT: { en: "Trinidad & Tobago", fr: "Trinité-et-Tobago" },
  TV: { en: "Tuvalu", fr: "Tuvalu" },
  TW: { en: "Taiwan", fr: "Taïwan" },
  TZ: { en: "Tanzania", fr: "Tanzanie" },
  UA: { en: "Ukraine", fr: "Ukraine" },
  UG: { en: "Uganda", fr: "Ouganda" },
  US: { en: "United States", fr: "États-Unis" },
  UY: { en: "Uruguay", fr: "Uruguay" },
  UZ: { en: "Uzbekistan", fr: "Ouzbékistan" },
  VA: { en: "Vatican City", fr: "État de la Cité du Vatican" },
  VC: { en: "St. Vincent & Grenadines", fr: "Saint-Vincent-et-les Grenadines" },
  VE: { en: "Venezuela", fr: "Venezuela" },
  VG: { en: "British Virgin Islands", fr: "Îles Vierges britanniques" },
  VI: { en: "U.S. Virgin Islands", fr: "Îles Vierges des États-Unis" },
  VN: { en: "Vietnam", fr: "Viêt Nam" },
  VU: { en: "Vanuatu", fr: "Vanuatu" },
  WF: { en: "Wallis & Futuna", fr: "Wallis-et-Futuna" },
  WS: { en: "Samoa", fr: "Samoa" },
  XK: { en: "Kosovo", fr: "Kosovo" },
  YE: { en: "Yemen", fr: "Yémen" },
  YT: { en: "Mayotte", fr: "Mayotte" },
  ZA: { en: "South Africa", fr: "Afrique du Sud" },
  ZM: { en: "Zambia", fr: "Zambie" },
  ZW: { en: "Zimbabwe", fr: "Zimbabwe" },
};
