// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // `dist` and `.expo` are build output -- `.expo/types/router.d.ts` is
    // generated by expo-router's typed-routes codegen and carries its own
    // eslint-disable header, which this config then reports as unused.
    // `android`/`ios` are prebuild output; they are gitignored today but
    // appear locally the moment anyone runs `expo prebuild`, and linting
    // generated native projects is never useful.
    ignores: ["dist/*", ".expo/*", "android/*", "ios/*"],
  },
  {
    // React Compiler rules from eslint-config-expo 57. Turning eslint on for
    // this workspace at all surfaced 26 findings across 17 screens; they were
    // parked at "warn" so that the tooling fix and the code fixes stayed
    // separate changes. `refs` and `immutability` have since been fixed and
    // are back at "error", which is what keeps them fixed.
    //
    // `set-state-in-effect` stays at "warn" for 12 remaining findings, and
    // they are NOT all the same thing:
    //
    //  * NINE are the plain `useEffect(() => { void loadThing(); }, [load])`
    //    data-load idiom (history, profile, progress/entries, payment/[id],
    //    notifications, plan, onboarding/plan, renew, offline-sync-context).
    //    Every setState in those is after an `await`; the rule simply cannot
    //    prove it. There is no better pattern available without adopting a
    //    data-fetching library or Suspense, which is an architecture decision
    //    and not a lint fix. Rewriting them to satisfy the rule would make
    //    the code worse, so they are deliberately left alone.
    //
    //  * THREE are genuine synchronous setStates: the lazy-load-on-tab-
    //    activation effects in classes/index.tsx (x2) and history/index.tsx.
    //    The rule's own advice -- move it to the event handler -- is right,
    //    but the active tab can also be set by a deep-link param rather than
    //    a press, so the fix has to keep a param-driven path. That needs its
    //    own change and its own device pass on both tab flows.
    //
    // Do not raise set-state-in-effect to "error" until those three are done;
    // the other nine would have to be suppressed individually, which is worse
    // than one honest rule-level warning.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "error",
      "react-hooks/immutability": "error",
    },
  },
]);
