// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // `dist` and `.expo` are build output -- `.expo/types/router.d.ts` is
    // generated by expo-router's typed-routes codegen and carries its own
    // eslint-disable header, which this config then reports as unused.
    // `android`/`ios` are prebuild output; they are gitignored today but
    // appear locally the moment anyone runs `expo prebuild`, and linting
    // generated native projects is never useful.
    ignores: ["dist/*", ".expo/*", "android/*", "ios/*"],
  },
  {
    // The React Compiler rules that ship in eslint-config-expo 57 report 26
    // findings across 17 existing screens. They are recorded as warnings
    // rather than silenced, and rather than being "fixed" in the same change
    // that first made linting possible at all.
    //
    // This is a deliberate baseline, not a suppression:
    //
    //  * Until now `expo lint` could not run in this repo at all (no eslint
    //    dependency), so none of this code has ever been linted. These are
    //    pre-existing findings surfaced by turning the tool on, not
    //    regressions introduced by anything.
    //
    //  * Most are legitimate, conservative-rule cases rather than bugs --
    //    `set-state-in-effect` fires on ordinary load-data-on-mount effects
    //    and on the hydration flag in use-color-scheme.web.ts. Rewriting 17
    //    production screens' effect and ref patterns is a real behavioural
    //    change to an app whose verification is a manual device pass, so it
    //    belongs in its own change with its own testing, not bundled into a
    //    tooling fix.
    //
    // Raise these back to "error" screen by screen as they are fixed and
    // device-tested. `pnpm --filter @gymos/mobile lint` prints all 26.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/immutability": "warn",
    },
  },
]);
